{% set name = "readlif" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 273de3847c9a4c832d9cd486c2bf0656b99f30c157a7781254664bd9c9ccce0d


build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - Pillow

test:
  imports:
    - readlif
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/nimne/readlif
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Fast Leica LIF file reader written in python
  doc_url: https://readlif.readthedocs.io/en/latest/
  dev_url: https://github.com/nimne/readlif

extra:
  recipe-maintainers:
    - nimne
    - JacksonMaxfield
